services:
 nginx:
    build: requirements/nginx/.
    container_name: nginx
    image: nginx
    ports:
        - "443:443"
    volumes:
        - wordpress:/var/www/html
    networks:
        - inception
    depends_on:
        wordpress:
            condition: service_healthy
    restart: always

 wordpress:
    build: requirements/wordpress/.
    container_name: wordpress
    image: wordpress
    env_file:
        - .env
    volumes:
        - wordpress:/var/www/html
    networks:
        - inception
    expose:
        - "9000"
    depends_on:
        mariadb:
            condition: service_healthy
    healthcheck:
        test: ["CMD", "wp", "--path=/var/www/html", "--allow-root", "core", "is-installed"]
        interval: 15s
        timeout: 10s
        retries: 3
        start_period: 15s
    restart: always

 mariadb:
    build: requirements/mariadb/.
    container_name: mariadb
    image: mariadb
    volumes:
        - mariadb:/var/lib/mysql
    networks:
        - inception
    env_file:
        - .env
    healthcheck:
        test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
        interval: 5s
        timeout: 5s
        retries: 10
        start_period: 3s
    restart: always

volumes:
    mariadb:
        name: mariadb
        driver: local
        driver_opts:
            device: /home/polmarti/data/mariadb
            o: bind
            type: none
    wordpress:
        name: wordpress
        driver: local
        driver_opts:
            device: /home/polmarti/data/wordpress
            o: bind
            type: none

networks:
    inception:
        driver: bridge

