services:
 nginx:
    build: requirements/nginx/.
    container_name: nginx
    image: nginx
    ports:
        - "443:443"
    volumes:
        - wordpress:/var/www/html
    networks:
        - inception
    depends_on:
        wordpress:
            condition: service_healthy
    restart: always

 wordpress:
    build: requirements/wordpress/.
    container_name: wordpress
    image: wordpress
    env_file:
        - .env
    volumes:
        - wordpress:/var/www/html
    networks:
        - inception
    depends_on:
        mariadb:
            condition: service_healthy
    healthcheck:
        test: ["CMD", "wp", "--path=/var/www/html", "--allow-root", "core", "is-installed"]
        interval: 15s
        timeout: 10s
        retries: 3
        start_period: 15s
    secrets:
      - MYSQL_USER
      - MYSQL_PASSWORD
      - WORDPRESS_ADMIN
      - WORDPRESS_ADMIN_PASS
      - WORDPRESS_ADMIN_EMAIL
      - WORDPRESS_USER
      - WORDPRESS_USER_PASS
      - WORDPRESS_EMAIL
    restart: always

 mariadb:
    build: requirements/mariadb/.
    container_name: mariadb
    image: mariadb
    volumes:
        - mariadb:/var/lib/mysql
    networks:
        - inception
    env_file:
        - .env
    healthcheck:
        test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
        interval: 5s
        timeout: 5s
        retries: 10
        start_period: 3s
    secrets:
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_ROOT_USER
      - MYSQL_ROOT_PASSWORD
    restart: always

volumes:
    mariadb:
        name: mariadb
        driver: local
        driver_opts:
            device: /home/polmarti/data/mariadb
            o: bind
            type: none
    wordpress:
        name: wordpress
        driver: local
        driver_opts:
            device: /home/polmarti/data/wordpress
            o: bind
            type: none

networks:
    inception:
        driver: bridge

secrets:
  WORDPRESS_ADMIN:
    file: ../secrets/wp_admin_user.txt
  WORDPRESS_ADMIN_PASS:
    file: ../secrets/wp_admin_pass.txt
  WORDPRESS_ADMIN_EMAIL:
    file: ../secrets/wp_admin_email.txt
  WORDPRESS_USER:
    file: ../secrets/wp_user.txt
  WORDPRESS_USER_PASS:
    file: ../secrets/wp_user_pass.txt
  WORDPRESS_EMAIL:
    file: ../secrets/wp_user_email.txt
  MYSQL_USER:
    file: ../secrets/db_user.txt
  MYSQL_PASSWORD:
    file: ../secrets/db_user_pass.txt
  MYSQL_ROOT_USER:
    file: ../secrets/db_root_user.txt
  MYSQL_ROOT_PASSWORD:
    file: ../secrets/db_root_pass.txt
