services:
 nginx:
    build: requirements/nginx/.
    container_name: nginx
    image: nginx
    ports:
        - "80:80"
        - "443:443"
    volumes:
        - wordpress:/var/www/html #remember should be (host vm)/home/polmarti/data
    networks:
        - inception
    depends_on:
        - wordpress
    restart: always

 wordpress:
    build: requirements/wordpress/.
    container_name: wordpress
    image: wordpress
    env_file:
        - .env
    volumes:
        - wordpress:/var/www/html
    networks:
        - inception
    expose:
        - "9000"
    depends_on:
        - mariadb
    restart: always

 mariadb:
    build: requirements/mariadb/.
    container_name: mariadb
    image: mariadb
    volumes:
        - mariadb:/var/lib/mysql
    env_file:
        - .env
    restart: always

volumes:
    mariadb:
        driver: local
        driver_opts:
            device: /home/polmarti/data/mariadb
            o: bind
            type: none
    wordpress:
        driver: local
        driver_opts:
            device: /home/polmarti/data/wordpress
            o: bind
            type: none

networks:
    inception:
        driver: bridge

