FROM debian:bullseye-slim

RUN apt-get update && apt-get install -y mariadb-server && apt-get clean && rm -rf /var/lib/apt/lists/*

#ENTRYPOINT ["mysql -u root"]
#RUN service mariadb start
#RUN mysql -u root o ENTRYPOINT [ "mysql -u root" ]?

#to build the dockerfile -> $docker build -t test . --debug