FROM debian:bullseye

RUN apt-get update && apt-get install -y mariadb-server && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN sed -i 's|user                    = mysql|user                    = root|' /etc/mysql/mariadb.conf.d/50-server.cnf
RUN sed -i 's|bind-address            = 127.0.0.1|#bind-address            = 127.0.0.1|' /etc/mysql/mariadb.conf.d/50-server.cnf
RUN sed -i '/skip-external-locking/a \port			= 3306' /etc/mysql/mariadb.conf.d/50-server.cnf
RUN sed -i '/skip-external-locking/a \socket			= /run/mysqld/mysqld.sock' /etc/mysql/mariadb.conf.d/50-server.cnf
RUN mkdir -p /run/mysqld
COPY ./tools/mariadb.sh /usr/local/bin
RUN chmod 777 /usr/local/bin/mariadb.sh

ENTRYPOINT ["/usr/local/bin/mariadb.sh"]
