FROM debian:bullseye-slim

RUN apt-get update && apt-get install -y nginx && apt-get clean && rm -rf /var/lib/apt/lists/*

COPY ./conf/nginx.conf /etc/nginx/sites-aviable/default
COPY ./test_html/index.html /usr/share/nginx/html/index.html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
