#Esta es la primera etapa de building
FROM debian:bullseye-slim

# Pendiente instalar tambien el ssl 
RUN apt-get update && apt-get install -y nginx && apt-get clean && rm -rf /var/lib/apt/lists/*

# Existen las carpetas sites-aviable y sites-enable, para poder visualizar el ejemplo debe estar en enable
# COPY ./conf/nginx.conf /etc/nginx/sites-aviable/default
COPY ./conf/nginx.conf /etc/nginx/sites-enable/default

COPY ./test_html/index.html /usr/share/nginx/html/index.html

# Se expone el puerto 80 de forma temporal, ya que para poder agregar el servicio de SSL/TLS
# se usa en el puerto 443
# EXPOSE 443
EXPOSE 80

# Esta es la etapa de run, donde se ejecuta la imagen
# El flag -g significa global y permite especificar una o mas directivas propias del .conf ("directiva1; directiva2; ...")
# Por defecto nginx termina al lanzarlo (se ejecuta en segundo plano), con las opcion de daemon off se queda en primer plano como PID 1
CMD ["nginx", "-g", "daemon off;"]

